routes/web.php
<?php

use App\Http\Controllers\Admin\ReportController as AdminReportController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::resource('report', ReportController::class)->except([
    'show',
]);
Route::get('report/{ticket_id}', [ReportController::class, 'show'])->name('report.show');
Route::post('report/search', [ReportController::class, 'search_ticket'])->name('report.search');

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {
    Route::get('report/{report}/log', [AdminReportController::class, 'log'])->name('report.log');
    Route::post('report/add-report-tracker', [AdminReportController::class, 'addReportTracker'])->name('report.addReportTracker');
    Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::resource('report', AdminReportController::class);
});

app/Models/Report.php
<?php

namespace App\Models;

use Spatie\MediaLibrary\HasMedia;
use Spatie\Activitylog\LogOptions;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\MediaLibrary\InteractsWithMedia;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Report extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia, LogsActivity;

    protected $guarded = [];

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
                ->logOnly(['title', 'description', 'status'])
                ->setDescriptionForEvent(fn(string $eventName) => "This model has been {$eventName}")
                ->useLogName('Report');
    }

    protected $fillable = [
        'reporter_id',
        'category_id',
        'ticket_id',
        'title',
        'description',
        'status',
    ];

    public function Reporter()
    {
        return $this->belongsTo(Reporter::class);
    }

    public function Category()
    {
        return $this->belongsTo(Category::class);
    }

    public function ReportTrackers()
    {
        return $this->hasMany(ReportTracker::class);
    }
}

app/Http/Controllers/Admin/ReportController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Report;
use App\Models\Category;
use App\Models\Reporter;
use Illuminate\Http\Request;
use App\Models\ReportTracker;
use App\Http\Controllers\Controller;
use Spatie\Activitylog\Models\Activity;
use Yajra\DataTables\Facades\DataTables;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        if (request()->ajax()) {
            $data = Report::join('reporters', 'reports.reporter_id', '=', 'reporters.id')->select('reports.*', 'reporters.*');
            return DataTables::of($data)
            ->addIndexColumn()
            ->addColumn('action', function ($item) {
                $button =
                    '<div class="d-flex gap-2">
                        <a href="'.route('admin.report.log', $item->id).'" class="btn btn-primary">Log</a>
                        <a href="'.route('admin.report.show', $item->id).'" class="btn btn-warning">Show</a>
                        <a href="'.route('admin.report.edit', $item->id).'" class="btn btn-secondary">Edit</a>
                        <form class="inline-block" action="'. route('admin.report.destroy', $item->id) .'" method="POST">
                            <button class="btn btn-danger" >
                                Delete
                            </button>
                        '. method_field('delete') . csrf_field() .'
                        </form>
                    </div>';
                    //'<div class="dropdown">
                    //    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    //        Action
                    //    </button>
                    //    <ul class="dropdown-menu">
                    //        <li><a class="dropdown-item" href="'.route('admin.report.show', $item->id).'">Edit</a></li>
                    //        <li><a class="dropdown-item" href="'.route('admin.report.edit', $item->id).'">Edit</a></li>
                    //        <li><a class="dropdown-item" href="#">Delete</a></li>
                    //    </ul>
                    //</div> ';
                return $button;
            })
            ->make();
        }
        return view('admin.report.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Report $report)
    {
        $report = Report::where('id', $report->id)->get();
        $reporter = Reporter::where('id', $report[0]->reporter_id)->get();

        if (!empty($report[0]->category_id)) {
            $category = Category::where('id', $report[0]->category_id)->get();
        } else {
            $category = [null];
        };

        return view('admin.report.show', [
            'report' => $report[0],
            'reporter' => $reporter[0],
            'category' => $category[0]
        ])->with('success', `Laporan dengan tiket {$report[0]->ticket_id} berhasil ditemukan.`);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Report $report)
    {
        $report = Report::where('id', $report->id)->get();
        $reporter = Reporter::where('id', $report[0]->reporter_id)->get();
        $categories = Category::all();

        $statuses = [
            'Pending',
            'Proses Administratif',
            'Proses Penanganan',
            'Selesai Ditangani',
            'Laporan Ditolak'
        ];

        return view('admin.report.form', [
            'report' => $report[0],
            'reporter' => $reporter[0],
            'statuses' => $statuses,
            'categories' => $categories
        ])->with('success', `Laporan dengan tiket {$report[0]->ticket_id} berhasil ditemukan.`);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Report $report)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Report $report)
    {
        $reporter = Reporter::where('id', $report->report_id);

        $report->clearMediaCollection('evidences');

        $reporter->delete();
        $report->delete();

        return redirect()->back();
    }

    public function addReportTracker(Request $request)
    {
        $reportTracker = ReportTracker::create([
            'report_id' => $request->report_id,
            'user_id' => $request->user_id,
            'status' => $request->status,
            'note' => $request->note,
        ]);

        $report = new Report();

        $report->where('id', $request->report_id)->update([
            'status' => $request->status,
            'category_id' => $request->category_id
        ]);

        return to_route('admin.report.index')->with('success', 'Laporan berhasil diperbarui.');
    }

    public function log(Report $report){
        return view('admin.report.log',[
            'logs' => Activity::where('subject_type', Report::class)->where('subject_id', $report->id)->latest()->get(),
            'report' => $report
        ]);
    }
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Models\Report;
use App\Models\Category;
use App\Models\Reporter;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Spatie\Activitylog\Models\Activity;
use App\Http\Requests\StoreReportRequest;
use App\Http\Requests\UpdateReportRequest;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('report.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('report.form', [
            'method' => 'POST',
            'reporter' => new Reporter(),
            'report' => new Report(),
            'route' => route('report.store')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'email' => 'required|email',
            'phone_number' => 'required',
            'identity_type' => 'required',
            'identity_number' => 'required',
            'pob' => 'required|string',
            'dob' => 'required',
            'address' => 'required',
            'title' => 'required',
            'description' => 'required',
            'evidences.*' => 'image|mimes:jpeg,png,jpg',
        ]);

        $reporter = Reporter::create([
            'name' => $request->name,
            'email' => $request->email,
            'phone_number' => $request->phone_number,
            'identity_type' => $request->identity_type,
            'identity_number' => $request->identity_number,
            'pob' => $request->pob,
            'dob' => $request->dob,
            'address' => $request->address,
        ]);

        $report = Report::create([
            'reporter_id' => $reporter->id,
            'ticket_id' => Str::random(16),
            'title' => $request->title,
            'description' => $request->description,
            'status' => 'Pending'
        ]);

        if ($request->hasFile('evidences')) {
            foreach ($request->file('evidences') as $evidence) {
                $report->addMedia($evidence)->usingFileName(Str::random(16).'')->toMediaCollection('evidences');
            }
        }

        return to_route('report.show', $report->ticket_id)->with('success', 'Laporan berhasil ditambahkan.');
    }

    /**
     * Display the specified resource.
     */
    public function show($ticket_id)
    {
        $report = Report::where('ticket_id', $ticket_id)->get();
        $reporter = Reporter::where('id', $report[0]->reporter_id)->get();

        if (!empty($report[0]->category_id)) {
            $category = Category::where('id', $report[0]->category_id)->get();
        } else {
            $category = [null];
        };

        return view('report.show', [
            'report' => $report[0],
            'reporter' => $reporter[0],
            'category' => $category[0]
        ])->with('success', `Laporan dengan tiket {$report[0]->ticket_id} berhasil ditemukan.`);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Report $report)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateReportRequest $request, Report $report)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Report $report)
    {
        //
    }

    public function search_ticket(Request $request)
    {
        $report = Report::where('ticket_id', $request->search_ticket)->first();

        if ($report) {
            return redirect()->route('report.show', $report->ticket_id)->with('success', 'Laporan berhasil ditemukan.');
        } else {
            return redirect()->back()->with('error', 'Laporan tidak ditemukan.');
        }
    }
}

resources/views/report/form.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="{{ $route }}" method="post" enctype="multipart/form-data">
                        @if ($method == 'PUT') @method('PUT') @endif
                        @csrf
                        <div class="mb-3">
                            <label for="name" class="form-label">Nama</label>
                            <input type="text" name="name" id="name" class="form-control" value="{{ old('name',$reporter->name) }}">
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" name="email" id="email" class="form-control" value="{{ old('email',$reporter->email) }}">
                        </div>
                        <div class="mb-3">
                            <label for="phone_number" class="form-label">Nomor HP</label>
                            <input type="text" name="phone_number" id="phone_number" class="form-control" value="{{ old('phone_number',$reporter->phone_number) }}">
                        </div>
                        <div class="mb-3">
                            <label for="identity_type" class="form-label">Tipe Identitas</label>
                            <select name="identity_type" id="identity_type" class="form-control">
                                <option value="">Choose type of identity</option>
                                <option value="" disabled>--------</option>
                                <option value="KTP">KTP</option>
                                <option value="SIM">SIM</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="identity_number" class="form-label">Nomor Identitas</label>
                            <input type="number" name="identity_number" id="identity_number" class="form-control" value="{{ old('identity_number',$reporter->identity_number) }}">
                        </div>
                        <div class="mb-3">
                            <label for="pob" class="form-label">Tempat Lahir</label>
                            <input type="text" name="pob" id="pob" class="form-control" value="{{ old('pob',$reporter->pob) }}">
                        </div>
                        <div class="mb-3">
                            <label for="dob" class="form-label">Tanggal Lahir</label>
                            <input type="date" name="dob" id="dob" class="form-control" value="{{ old('dob',$reporter->dob) }}">
                        </div>
                        <div class="mb-3">
                            <label for="address" class="form-label">Alamat</label>
                            <input type="text" name="address" id="address" class="form-control" value="{{ old('address',$reporter->address) }}">
                        </div>
                        <div class="mb-3">
                            <label for="title" class="form-label">Judul Laporan</label>
                            <input type="text" name="title" id="title" class="form-control" value="{{ old('title',$report->title) }}">
                        </div>
                        <div class="mb-3">
                            <label for="description" class="form-label">Deskripsi Laporan</label>
                            <textarea name="description" id="description" class="form-control">{{ old('description',$reporter->description) }}</textarea>
                        </div>
                        <div class="mb-3">
                            <label for="evidences" class="form-label">Bukti Laporan</label>
                            <input type="file" name="evidences[]" id="evidences" class="form-control" multiple>
                        </div>
                        <button type="submit" class="btn btn-primary">
                            Buat Laporan
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/report/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        Halaman pengaduan - Cari laporan anda berdasarkan tiket laporan atau buat laporan baru
                    </div>
                    <div class="card-body">
                        <div class="accordion-item">
                            <div class="accordion-body">
                                <form action="{{ route('report.search') }}" method="post">
                                    @csrf
                                    <div class="mb-3">
                                        <label for="search_ticket" class="form-label">Masukkan nomor tiket laporan anda</label>
                                        <input type="text" name="search_ticket" id="search_ticket" class="form-control" placeholder="Cari Tiket..." value="">
                                    </div>

                                    <div class="d-flex justify-content-between">
                                        <a href="{{ route('report.create') }}" class="btn btn-outline-success">
                                            Buat laporan baru
                                        </a>
                                        <button type="submit" class="btn btn-primary">
                                            Cari laporan anda
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/report/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div>
                            Detail Laporan - {{ $report->ticket_id }}
                        </div>
                        <div>
                            <a href="{{ route('report.index') }}" class="btn btn-danger">Kembali ke pencarian</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="accordion-item">
                            <div class="accordion-body">
                                <p class="list-group-item">
                                    <strong>Nomor tiket:</strong>
                                    {{ $report->ticket_id }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Dibuat pada:</strong>
                                    {{ date('j F Y, H:i', strtotime($report->created_at)) }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Status:</strong>
                                    {{ $report->status }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Kategori:</strong>
                                    @if (is_null($category))
                                        Kategori belum ditentukan!
                                    @else
                                        {{ $category->name}}
                                    @endif
                                </p>
                                <p class="list-group-item">
                                    <strong>Nama Pelapor:</strong>
                                    {{ $reporter->name }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Email Pelapor:</strong>
                                    {{ $reporter->email }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Nomor HP Pelapor:</strong>
                                    {{ $reporter->phone_number }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Tipe Identitas Pelapor:</strong>
                                    {{ $reporter->identity_type }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Nomor Identitas Pelapor:</strong>
                                    {{ $reporter->identity_number }}
                                </p>
                                <p class="list-group-item">
                                    <strong>TTL Pelapor:</strong>
                                    {{ $reporter->pob.', '.date('j F Y', strtotime($reporter->dob)) }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Alamat Pelapor:</strong>
                                    {{ $reporter->address }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Judul Laporan:</strong>
                                    {{ $report->title }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Content:</strong>
                                    {{ $report->description }}
                                </p>
                                <p class="list-group-item mb-4">
                                    <strong>Bukti Laporan:</strong>
                                </p>
                                @foreach ($report->getMedia('evidences') as $evidence)
                                    <img src="{{ $evidence->getUrl() }}" width="200" class="me-4" alt="Bukti Laporan">
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection