routes/web.php
<?php

use App\Http\Controllers\Admin\ReportController as AdminReportController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::resource('report', ReportController::class)->except([
    'show',
]);
Route::get('report/{ticket_id}', [ReportController::class, 'show'])->name('report.show');
Route::post('report/search', [ReportController::class, 'search_ticket'])->name('report.search');

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {
    Route::get('report/{report}/log', [AdminReportController::class, 'log'])->name('report.log');
    Route::post('report/add-report-tracker', [AdminReportController::class, 'addReportTracker'])->name('report.addReportTracker');
    Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::resource('report', AdminReportController::class);
});

app/Models/Report.php
<?php

namespace App\Models;

use Spatie\MediaLibrary\HasMedia;
use Spatie\Activitylog\LogOptions;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\MediaLibrary\InteractsWithMedia;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Report extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia, LogsActivity;

    protected $guarded = [];

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
                ->logOnly(['title', 'description', 'status'])
                ->setDescriptionForEvent(fn(string $eventName) => "This model has been {$eventName}")
                ->useLogName('Report');
    }

    protected $fillable = [
        'reporter_id',
        'category_id',
        'ticket_id',
        'title',
        'description',
        'status',
    ];

    public function Reporter()
    {
        return $this->belongsTo(Reporter::class);
    }

    public function Category()
    {
        return $this->belongsTo(Category::class);
    }

    public function ReportTrackers()
    {
        return $this->hasMany(ReportTracker::class);
    }
}

app/Http/Controllers/Admin/ReportController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Report;
use App\Models\Category;
use App\Models\Reporter;
use Illuminate\Http\Request;
use App\Models\ReportTracker;
use App\Http\Controllers\Controller;
use Spatie\Activitylog\Models\Activity;
use Yajra\DataTables\Facades\DataTables;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        if (request()->ajax()) {
            $data = Report::join('reporters', 'reports.reporter_id', '=', 'reporters.id')->select('reports.*', 'reporters.*');
            return DataTables::of($data)
            ->addIndexColumn()
            ->addColumn('action', function ($item) {
                $button =
                    '<div class="d-flex gap-2">
                        <a href="'.route('admin.report.log', $item->id).'" class="btn btn-primary">Log</a>
                        <a href="'.route('admin.report.show', $item->id).'" class="btn btn-warning">Show</a>
                        <a href="'.route('admin.report.edit', $item->id).'" class="btn btn-secondary">Edit</a>
                        <form class="inline-block" action="'. route('admin.report.destroy', $item->id) .'" method="POST">
                            <button class="btn btn-danger" >
                                Delete
                            </button>
                        '. method_field('delete') . csrf_field() .'
                        </form>
                    </div>';
                    //'<div class="dropdown">
                    //    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    //        Action
                    //    </button>
                    //    <ul class="dropdown-menu">
                    //        <li><a class="dropdown-item" href="'.route('admin.report.show', $item->id).'">Edit</a></li>
                    //        <li><a class="dropdown-item" href="'.route('admin.report.edit', $item->id).'">Edit</a></li>
                    //        <li><a class="dropdown-item" href="#">Delete</a></li>
                    //    </ul>
                    //</div> ';
                return $button;
            })
            ->make();
        }
        return view('admin.report.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Report $report)
    {
        $report = Report::where('id', $report->id)->get();
        $reporter = Reporter::where('id', $report[0]->reporter_id)->get();

        if (!empty($report[0]->category_id)) {
            $category = Category::where('id', $report[0]->category_id)->get();
        } else {
            $category = [null];
        };

        return view('admin.report.show', [
            'report' => $report[0],
            'reporter' => $reporter[0],
            'category' => $category[0]
        ])->with('success', `Laporan dengan tiket {$report[0]->ticket_id} berhasil ditemukan.`);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Report $report)
    {
        $report = Report::where('id', $report->id)->get();
        $reporter = Reporter::where('id', $report[0]->reporter_id)->get();
        $categories = Category::all();

        $statuses = [
            'Pending',
            'Proses Administratif',
            'Proses Penanganan',
            'Selesai Ditangani',
            'Laporan Ditolak'
        ];

        return view('admin.report.form', [
            'report' => $report[0],
            'reporter' => $reporter[0],
            'statuses' => $statuses,
            'categories' => $categories
        ])->with('success', `Laporan dengan tiket {$report[0]->ticket_id} berhasil ditemukan.`);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Report $report)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Report $report)
    {
        $reporter = Reporter::where('id', $report->report_id);

        $report->clearMediaCollection('evidences');

        $reporter->delete();
        $report->delete();

        return redirect()->back();
    }

    public function addReportTracker(Request $request)
    {
        $reportTracker = ReportTracker::create([
            'report_id' => $request->report_id,
            'user_id' => $request->user_id,
            'status' => $request->status,
            'note' => $request->note,
        ]);

        $report = new Report();

        $report->where('id', $request->report_id)->update([
            'status' => $request->status,
            'category_id' => $request->category_id
        ]);

        return to_route('admin.report.index')->with('success', 'Laporan berhasil diperbarui.');
    }

    public function log(Report $report){
        return view('admin.report.log',[
            'logs' => Activity::where('subject_type', Report::class)->where('subject_id', $report->id)->latest()->get(),
            'report' => $report
        ]);
    }
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Models\Report;
use App\Models\Category;
use App\Models\Reporter;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Spatie\Activitylog\Models\Activity;
use App\Http\Requests\StoreReportRequest;
use App\Http\Requests\UpdateReportRequest;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('report.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('report.form', [
            'method' => 'POST',
            'reporter' => new Reporter(),
            'report' => new Report(),
            'route' => route('report.store')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'email' => 'required|email',
            'phone_number' => 'required',
            'identity_type' => 'required',
            'identity_number' => 'required',
            'pob' => 'required|string',
            'dob' => 'required',
            'address' => 'required',
            'title' => 'required',
            'description' => 'required',
            'evidences.*' => 'image|mimes:jpeg,png,jpg',
        ]);

        $reporter = Reporter::create([
            'name' => $request->name,
            'email' => $request->email,
            'phone_number' => $request->phone_number,
            'identity_type' => $request->identity_type,
            'identity_number' => $request->identity_number,
            'pob' => $request->pob,
            'dob' => $request->dob,
            'address' => $request->address,
        ]);

        $report = Report::create([
            'reporter_id' => $reporter->id,
            'ticket_id' => Str::random(16),
            'title' => $request->title,
            'description' => $request->description,
            'status' => 'Pending'
        ]);

        if ($request->hasFile('evidences')) {
            foreach ($request->file('evidences') as $evidence) {
                $report->addMedia($evidence)->usingFileName(Str::random(16).'')->toMediaCollection('evidences');
            }
        }

        return to_route('report.show', $report->ticket_id)->with('success', 'Laporan berhasil ditambahkan.');
    }

    /**
     * Display the specified resource.
     */
    public function show($ticket_id)
    {
        $report = Report::where('ticket_id', $ticket_id)->get();
        $reporter = Reporter::where('id', $report[0]->reporter_id)->get();

        if (!empty($report[0]->category_id)) {
            $category = Category::where('id', $report[0]->category_id)->get();
        } else {
            $category = [null];
        };

        return view('report.show', [
            'report' => $report[0],
            'reporter' => $reporter[0],
            'category' => $category[0]
        ])->with('success', `Laporan dengan tiket {$report[0]->ticket_id} berhasil ditemukan.`);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Report $report)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateReportRequest $request, Report $report)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Report $report)
    {
        //
    }

    public function search_ticket(Request $request)
    {
        $report = Report::where('ticket_id', $request->search_ticket)->first();

        if ($report) {
            return redirect()->route('report.show', $report->ticket_id)->with('success', 'Laporan berhasil ditemukan.');
        } else {
            return redirect()->back()->with('error', 'Laporan tidak ditemukan.');
        }
    }
}

resources/views/admin/report/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div>
                            Detail Laporan - {{ $report->ticket_id }}
                        </div>
                        <div>
                            <a href="{{ route('admin.report.index') }}" class="btn btn-danger">Kembali ke Dashboard</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="accordion-item">
                            <div class="accordion-body">
                                <form action="{{ route('admin.report.addReportTracker') }}" method="post">
                                    @csrf
                                    <div class="mb-3">
                                        <label for="status" class="form-label">Status Pengaduan</label>
                                        <select name="status" id="status" class="form-control">
                                            <option value="">Pilih status</option>
                                            <option value="" disabled>--------</option>
                                            @foreach ($statuses as $status)
                                                <option value="{{ $status }}" {{ $status == $report->status ? 'selected' : '' }}>{{ $status }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="mb-3">
                                        <label for="category_id" class="form-label">Kategori</label>
                                        <select name="category_id" id="category_id" class="form-control">
                                            <option value="">Pilih Kategori</option>
                                            <option value="" disabled>--------</option>
                                            @foreach ($categories as $category)
                                                <option value="{{ $category->id }}" {{ $report->category_id == $category->id ? 'selected' : '' }}>{{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="mb-3">
                                        <label for="note" class="form-label">Deskripsi</label>
                                        <textarea name="note" id="note" class="form-control">{{ old('note') }}</textarea>
                                    </div>
                                    <input type="hidden" name="report_id" id="report_id" class="form-control" value="{{ $report->id }}">
                                    <input type="hidden" name="user_id" id="user_id" class="form-control" value="{{ Auth::id() }}">
                                    <div class="d-flex justify-content-end">
                                        <button type="submit" class="btn btn-primary">
                                            Ubah status
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <hr class="mx-4">
                    <div class="card-body">
                        <div class="accordion-item">
                            <div class="accordion-body">
                                <p class="list-group-item">
                                    <strong>Nomor tiket:</strong>
                                    {{ $report->ticket_id }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Dibuat pada:</strong>
                                    {{ date('j F Y, H:i', strtotime($report->created_at)) }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Status:</strong>
                                    {{ $report->status }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Nama Pelapor:</strong>
                                    {{ $reporter->name }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Email Pelapor:</strong>
                                    {{ $reporter->email }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Nomor HP Pelapor:</strong>
                                    {{ $reporter->phone_number }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Tipe Identitas Pelapor:</strong>
                                    {{ $reporter->identity_type }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Nomor Identitas Pelapor:</strong>
                                    {{ $reporter->identity_number }}
                                </p>
                                <p class="list-group-item">
                                    <strong>TTL Pelapor:</strong>
                                    {{ $reporter->pob.', '.date('j F Y', strtotime($reporter->dob)) }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Alamat Pelapor:</strong>
                                    {{ $reporter->address }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Judul Laporan:</strong>
                                    {{ $report->title }}
                                </p>
                                <p class="list-group-item">
                                    <strong>Content:</strong>
                                    {{ $report->description }}
                                </p>
                                <p class="list-group-item mb-4">
                                    <strong>Bukti Laporan:</strong>
                                </p>
                                @foreach ($report->getMedia('evidences') as $evidence)
                                    <img src="{{ $evidence->getUrl() }}" width="200" class="me-4" alt="Bukti Laporan">
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/report/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container py-5">
        <div class="row">
            <h2 class="fs-5 fw-bold text-center mb-4">
                Data Laporan
            </h2>
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="userTable" class="table table-striped table-bordered mb-3" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th>Judul Laporan</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#userTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ url()->current() }}',
                columns: [
                    {
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        orderable: false,
                        searchable: false,
                        width: '5%'
                    },
                    {
                        data: 'name',
                        name: 'name',
                        orderable: true,
                        searchable: true,
                        width: '25%'
                    },
                    {
                        data: 'email',
                        name: 'email',
                        orderable: true,
                        searchable: true,
                        width: '20%'
                    },
                    {
                        data: 'phone_number',
                        name: 'phone_number',
                        orderable: true,
                        searchable: true,
                        width: '15%'
                    },
                    {
                        data: 'title',
                        name: 'title',
                        orderable: true,
                        searchable: true,
                        width: '20%'
                    },
                    {
                        data: 'status',
                        name: 'status',
                        orderable: true,
                        searchable: true,
                        width: '20%'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false,
                        width: '10%'
                    }
                ]
            });
            });
    </script>
@endsection

resources/views/admin/report/log.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div>
                        Aktivitas Laporan - {{ $report->ticket_id }}
                    </div>
                    <div>
                        <a href="{{ route('admin.report.index') }}" class="btn btn-danger">Kembali ke dashboard</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="accordion" id="accordionExample">
                        @forelse ($logs as $key => $log)
                        <div class="accordion-item">
                            <h2 class="accordion-header">
                                <button class="accordion-button {{ $key != 0 ? 'collapsed' : '' }}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ $key }}" aria-expanded="true" aria-controls="collapse-{{ $key }}">
                                <span>{{ $log->description }}</span> <small class="text-muted ms-2 pb-1">({{ $log->created_at->diffForHumans() }})</small>
                                </button>
                            </h2>
                            <div id="collapse-{{ $key }}" class="accordion-collapse collapse {{ $key == 0 ? 'show' : '' }}" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    @if ($log->event == 'updated')
                                    <ul class="list-group">
                                        {{--['title', 'description', 'status', 'category_id']--}}
                                        <li class="list-group-item bg-secondary text-white">Old Data</li>
                                        <li class="list-group-item"><strong>Title:</strong> {{ $log['properties']['old']['title'] }}</li>
                                        <li class="list-group-item"><strong>Description:</strong> {{ $log['properties']['old']['description'] }}</li>
                                        <li class="list-group-item"><strong>Status:</strong> {{ $log['properties']['old']['status'] }}</li>
                                        <li class="list-group-item"><strong>Category:</strong> {{ $log['properties']['old']['category_id'] }}</li>
                                        <li class="list-group-item bg-secondary text-white">New Data</li>
                                        <li class="list-group-item"><strong>Title:</strong> {{ $log['properties']['attributes']['title'] }}</li>
                                        <li class="list-group-item"><strong>Description:</strong> {{ $log['properties']['attributes']['description'] }}</li>
                                        <li class="list-group-item"><strong>Status:</strong> {{ $log['properties']['attributes']['status'] }}</li>
                                        <li class="list-group-item"><strong>Category:</strong> {{ $log['properties']['attributes']['category_id'] }}</li>
                                    </ul>
                                    @else
                                    {{ $log->description }}
                                    @endif
                                </div>
                            </div>
                        </div>
                        @empty
                        <div class="accordion-item">
                            <h2 class="accordion-header">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ $key }}" aria-expanded="true" aria-controls="collapse-{{ $key }}">
                                No activity found.
                                </button>
                            </h2>
                        </div>
                        @endforelse
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/report/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div>
                            Detail Laporan - {{ $report->ticket_id }}
                        </div>
                        <div>
                            <a href="{{ route('admin.report.index') }}" class="btn btn-danger">Kembali ke dashboard</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="accordion-item">
                            <div class="accordion-body">
                                <p class="list-group-item"><strong>Nomor tiket:</strong> {{ $report->ticket_id }}</p>
                                <p class="list-group-item"><strong>Dibuat pada:</strong> {{ date('j F Y, H:i', strtotime($report->created_at)) }}</p>
                                <p class="list-group-item"><strong>Status:</strong> {{ $report->status }}</p>
                                <p class="list-group-item"><strong>Kategori:</strong>
                                    @if (is_null($category))
                                        Kategori belum ditentukan!
                                    @else
                                        {{ $category->name}}
                                    @endif
                                </p>
                                <p class="list-group-item"><strong>Nama Pelapor:</strong> {{ $reporter->name }}</p>
                                <p class="list-group-item"><strong>Email Pelapor:</strong> {{ $reporter->email }}</p>
                                <p class="list-group-item"><strong>Nomor HP Pelapor:</strong> {{ $reporter->phone_number }}</p>
                                <p class="list-group-item"><strong>Tipe Identitas Pelapor:</strong> {{ $reporter->identity_type }}</p>
                                <p class="list-group-item"><strong>Nomor Identitas Pelapor:</strong> {{ $reporter->identity_number }}</p>
                                <p class="list-group-item"><strong>TTL Pelapor:</strong> {{ $reporter->pob.', '.date('j F Y', strtotime($reporter->dob)) }}</p>
                                <p class="list-group-item"><strong>Alamat Pelapor:</strong> {{ $reporter->address }}</p>
                                <p class="list-group-item"><strong>Judul Laporan:</strong> {{ $report->title }}</p>
                                <p class="list-group-item"><strong>Content:</strong> {{ $report->description }}</p>
                                <p class="list-group-item mb-4"><strong>Bukti Laporan:</strong></p>
                                @foreach ($report->getMedia('evidences') as $evidence)
                                    <img src="{{ $evidence->getUrl() }}" width="200" class="me-4" alt="Bukti Laporan">
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection